#!/bin/tcsh
#PBS -N firsthum
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe
#PBS -o /sciclone/geounder/dev/geoBoundaries/scripts/geoBoundaryBot/external/jobFiles

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load python/usermodules

unsetenv PYTHONPATH

conda activate hdx
cd /sciclone/geounder/dev/geoBoundaries/scripts/geoBoundaryBot/external
python fifthhum.py vortex >& fifththum.out